config/routes.rb
Rails.application.routes.draw do

  #Root route:
  root :to => 'frontpage#index'

  get 'show/:permalink', :to => 'public#show', :as => 'public_show'

  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  get 'public/index'
  get 'about/index'
  get 'contact/index'
  get 'frontpage/index'
  get 'stopmaps_v/index'
  get 'stopmaps_e/index'
  
  get 'track/:id/:stop_id', :to => 'tracks#stopdelete', :as => 'delete_stop_in_track'

  #get 'sketch-map-track-list.json' => 'static#sketch-map-track-list', :defaults => { :format => 'json' }

  resources :admin_users, :except => [:show] do
    member do
      get :delete
    end
  end

  resources :tags do
    member do
      get :delete
    end
  end

  resources :stops do
    member do
      get :delete
    end
  end

  resources :tracks do
    member do
      get :delete
    end
  end

  resources :locations do
    member do
      get :delete
    end
  end

  resources :names do
    member do
      get :delete
    end
  end

  resources :finished_dates do
    member do
      get :delete
    end
  end

  resources :pitches do
    member do
      get :delete
    end
  end

  resources :stop_maps do
    member do
      get :delete
    end
  end

  resources :keys do
    member do
      get :delete
    end
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord

  has_secure_password

  has_and_belongs_to_many :tags
  has_and_belongs_to_many :tracks

  scope :sorted, lambda { order("last_name ASC", "first_name ASC") }
  
  #EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i

  validates :first_name, :presence => true,
                         :length => { :maximum => 25 }
  validates :last_name, :presence => true,
                        :length => { :maximum => 50 }
  validates :username, :presence => true,
                       :length => { :within => 8..25 },
                       :uniqueness => true
  validates :email, :presence => true,
                    :length => { :maximum => 100 },
                    #:format => EMAIL_REGEX,
                    :confirmation => true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/key.rb
class Key < ApplicationRecord

  has_secure_password

  scope :sorted, lambda { order("name ASC") }

end

app/models/stop.rb
class Stop < ApplicationRecord

  has_and_belongs_to_many :tracks

  scope :sorted, lambda { order("stop_number ASC") }

end

app/models/tag.rb
class Tag < ApplicationRecord

  has_and_belongs_to_many :tracks

  scope :visible, lambda { where(:visible => true) }
  scope :invisible, lambda { where(:visible => false) }
  scope :sorted, lambda { order("name ASC") }

end

app/models/track.rb
class Track < ApplicationRecord

  has_and_belongs_to_many :tags
  has_and_belongs_to_many :stops #må ha denne for ellers leter etter stops_tracks alfabetisk join

  has_attached_file :sound
  has_attached_file :image

  scope :visible, lambda { where(:visible => true) }
  scope :invisible, lambda { where(:visible => false) }
  scope :sorted, lambda { order("name ASC") }
  scope :sorted_by_name, lambda { order("track_number ASC", "track_version ASC") }
  scope :sorted_by_date_finished, lambda { order("date_finished DESC") }
  scope :sorted_by_pitch, lambda { order("pitch ASC") }
  scope :sorted_by_location, lambda { order("location_finished ASC") }
  scope :sorted_by_name_DESC, lambda { order("track_number DESC") }

  do_not_validate_attachment_file_type :sound
  #validates_attachment_content_type :sound, :content_type => ['audio/mp3', "audio/wav", "audio/mpeg", 'application/x-mp3'], :if => :sound?

  do_not_validate_attachment_file_type :image
  #validates_attachment :image, :content_type => [content_type: "gif", "png", "jpg", "jpeg"]

end

app/controllers/names_controller.rb
class NamesController < ApplicationController

  layout 'names'

  def index
    @tracks=Array.new
    tracknumbers = Track.select(:track_number).distinct.sorted_by_name
    tracknumbers.each do |tn|
      @tracks.concat Track.where(track_number: tn.track_number).limit(1)
    end
  end

  def show
    singletrack=Track.find(params[:id])
    @tracks = Track.where("track_number=?", singletrack.track_number)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/frontpage_helper.rb
module FrontpageHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/helpers/pitches_helper.rb
module PitchesHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/stop_map_helper.rb
module StopMapHelper
end

app/helpers/stopmaps_e_helper.rb
module StopmapsEHelper
end

app/helpers/stopmaps_v_helper.rb
module StopmapsVHelper
end

app/helpers/stops_helper.rb
module StopsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/names/index.html.erb
<% @page_title = "A Field Guide to Torn Tracks" %>

<div class="tracks contentnames">

  <p>&nbsp;</p>

  <h2>Index</h2>
  <p>&nbsp;</p>
  <table class="listing" summary="Track list"

    <tr class="header">
      <th>Tracks</th>
      <th> </th>
      <th> </th>
    </tr>
    <% @tracks.each do |track| %>

    <tr>
      <td><%= track.name %><%= track.track_number %></td>
      <td>&nbsp; &nbsp;</td>
      <td><%= link_to "Show", name_path(track) %></td>
    </tr>
  <% end %>
  </table>
</div>

app/views/names/show.html.erb
<% @page_title = "A Field Guide to Torn Tracks" %>

<div class="contentnames">
  <p>&nbsp;</p>
<%= link_to("<< Back to Index", names_path) %><br>
</div>
<div class="contentnames2">
    <div class="contentnames-inner">
      <h3 class="names-heading"> Versions available:</h3>
      
      <% avlen=0 %>
      <% avpit=0 %>

      <ul id="playlist" style="list-style-type:none">
        <% @tracks.each do |track| %>
          <li>
            <button class="playbutton"><%= link_to("▶", track.sound.to_s) %></button>
            <%= track.name %><%= track.track_number %> <i><%= track.track_version %></i>
          </li>
          <% avlen+=track.length.to_i %>
          <% avpit+=track.pitch %>
        <% end %>
      </ul>

      <audio class="name-audio" id="audio" controls controlsList="nodownload" preload="none">
        <source src="<%= @tracks[0].sound %>" type="audio/mpeg">
        Your browser does not support the audio element.
      </audio>

      <ul>
        <li>Average Length: <%= Time.at(avlen/@tracks.size).utc.strftime("%M:%S")%> min.</li>
        <li>Average Pitch: <%= (avpit/@tracks.size).round(2) %> Hz</li>
      </ul>

      <div class="map-element">
        <p>Where the tracks were made:</p>
        <br>
        <div id="custom_style_names" style='width: 100%; height: 300px;'>
			    <div id="OSMmap"></div>
		    </div>
		  </div>
	  </div>
</div>
   
  </p>
</div>

<script>
  $(document).ready(function () {
  	init();
  	function init(){
  		var current = 0;
  		var audio = $('#audio');
  		var playlist = $('#playlist');
  		var tracks = playlist.find('li a');
  		var len = tracks.length - 1;
  		audio[0].volume = .10;
  		//audio[0].play();
  		playlist.on('click','a', function(e){
  			e.preventDefault();
  			link = $(this);
  			current = link.parent().index();
  			run(link, audio[0]);
  		});
  		audio[0].addEventListener('ended',function(e){
  			current++;
  			if(current == len){
  				current = 0;
  				link = playlist.find('a')[0];
  			}else{
  				link = playlist.find('a')[current];
  			}
  			run($(link),audio[0]);
  		});
  	}
  	function run(link, player){
  			player.src = link.attr('href');
  			par = link.parent();
  			par.addClass('active').siblings().removeClass('active');
  			player.load();
  			player.play();
  	}
  });
</script>