config/routes.rb
Rails.application.routes.draw do

  #Root route:
  root :to => 'frontpage#index'

  get 'show/:permalink', :to => 'public#show', :as => 'public_show'

  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  get 'public/index'
  get 'about/index'
  get 'contact/index'
  get 'frontpage/index'
  get 'stopmaps_v/index'
  get 'stopmaps_e/index'
  
  get 'track/:id/:stop_id', :to => 'tracks#stopdelete', :as => 'delete_stop_in_track'

  #get 'sketch-map-track-list.json' => 'static#sketch-map-track-list', :defaults => { :format => 'json' }

  resources :admin_users, :except => [:show] do
    member do
      get :delete
    end
  end

  resources :tags do
    member do
      get :delete
    end
  end

  resources :stops do
    member do
      get :delete
    end
  end

  resources :tracks do
    member do
      get :delete
    end
  end

  resources :locations do
    member do
      get :delete
    end
  end

  resources :names do
    member do
      get :delete
    end
  end

  resources :finished_dates do
    member do
      get :delete
    end
  end

  resources :pitches do
    member do
      get :delete
    end
  end

  resources :stop_maps do
    member do
      get :delete
    end
  end

  resources :keys do
    member do
      get :delete
    end
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord

  has_secure_password

  has_and_belongs_to_many :tags
  has_and_belongs_to_many :tracks

  scope :sorted, lambda { order("last_name ASC", "first_name ASC") }
  
  #EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i

  validates :first_name, :presence => true,
                         :length => { :maximum => 25 }
  validates :last_name, :presence => true,
                        :length => { :maximum => 50 }
  validates :username, :presence => true,
                       :length => { :within => 8..25 },
                       :uniqueness => true
  validates :email, :presence => true,
                    :length => { :maximum => 100 },
                    #:format => EMAIL_REGEX,
                    :confirmation => true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/key.rb
class Key < ApplicationRecord

  has_secure_password

  scope :sorted, lambda { order("name ASC") }

end

app/models/stop.rb
class Stop < ApplicationRecord

  has_and_belongs_to_many :tracks

  scope :sorted, lambda { order("stop_number ASC") }

end

app/models/tag.rb
class Tag < ApplicationRecord

  has_and_belongs_to_many :tracks

  scope :visible, lambda { where(:visible => true) }
  scope :invisible, lambda { where(:visible => false) }
  scope :sorted, lambda { order("name ASC") }

end

app/models/track.rb
class Track < ApplicationRecord

  has_and_belongs_to_many :tags
  has_and_belongs_to_many :stops #må ha denne for ellers leter etter stops_tracks alfabetisk join

  has_attached_file :sound
  has_attached_file :image

  scope :visible, lambda { where(:visible => true) }
  scope :invisible, lambda { where(:visible => false) }
  scope :sorted, lambda { order("name ASC") }
  scope :sorted_by_name, lambda { order("track_number ASC", "track_version ASC") }
  scope :sorted_by_date_finished, lambda { order("date_finished DESC") }
  scope :sorted_by_pitch, lambda { order("pitch ASC") }
  scope :sorted_by_location, lambda { order("location_finished ASC") }
  scope :sorted_by_name_DESC, lambda { order("track_number DESC") }

  do_not_validate_attachment_file_type :sound
  #validates_attachment_content_type :sound, :content_type => ['audio/mp3', "audio/wav", "audio/mpeg", 'application/x-mp3'], :if => :sound?

  do_not_validate_attachment_file_type :image
  #validates_attachment :image, :content_type => [content_type: "gif", "png", "jpg", "jpeg"]

end

app/controllers/stops_controller.rb
class StopsController < ApplicationController

  before_action :confirm_logged_in

  layout 'admin'

def index
  @stops = Stop.sorted
end

def show
  @stop = Stop.find(params[:id])
end

def new
  @stop = Stop.new(:stop_number => 'Default')
end

def create

  # Save object
  # Regne om fra HH:MM:SS til sekunder
  string_sec=params[:stop][:stop_time]
  params[:stop][:stop_time]=string_sec.split(':').inject(0){|a,m| a=a * 60 + m.to_i}
  @stop = Stop.new(stop_params)
  if @stop.save
    # legge stop inn i tilhørende track gjennom join
    tracktostop=Track.find(params[:stop][:track_id])
    tracktostop.stops << @stop
    redirect_to(stops_path)
  else
    render('new')
  end
end

def edit
  @stop = Stop.find(params[:id])
end

def update
  @stop = Stop.find(params[:id])
  # Regne om fra HH:MM:SS til sekunder
  string_sec=params[:stop][:stop_time]
  params[:stop][:stop_time]=string_sec.split(':').inject(0){|a,m| a=a * 60 + m.to_i}

  if @stop.update_attributes(stop_params)
    # legge stop inn i tilhørende track gjennom join
    tracktostop=Track.find(params[:stop][:track_id])
    tracktostop.stops << @stop
    redirect_to(stop_path(@stop))
    flash[:notice] = "Stop '#{@stop.stop_number}' updated succesfully."
  else
    render('edit')
  end
end

def delete
  @stop = Stop.find(params[:id])
end

def destroy
  @stop = Stop.find(params[:id])
  @stop.destroy
  redirect_to(stops_path)
  flash[:notice] = "Stop '#{@stop.stop_number}' destroyed succesfully."
end

private
def stop_params
  params.require(:stop).permit(:stop_number, :stop_time, :track_id, :stop_title)
end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/frontpage_helper.rb
module FrontpageHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/helpers/pitches_helper.rb
module PitchesHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/stop_map_helper.rb
module StopMapHelper
end

app/helpers/stopmaps_e_helper.rb
module StopmapsEHelper
end

app/helpers/stopmaps_v_helper.rb
module StopmapsVHelper
end

app/helpers/stops_helper.rb
module StopsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/stops/_form.html.erb
<table summary="Summary from fields">
  <tr>
    <th>Title of the stop</th>
    <td><%= f.text_field(:stop_title) %></td>
  </tr>

  <tr>
    <th>Stop-track (track/sound of stop)</th>
    <td><%= f.number_field(:stop_number) %></td>
  </tr>

  <tr>
    <th>Time of stop (Format: HH:MM:SS)</th>
    <td><%= f.text_field(:stop_time) %></td>
  </tr>

  <tr>
    <th>Track ID (track containing this stop)</th>
    <td><%= f.number_field(:track_id) %></td>
  </tr>
</table>

app/views/stops/delete.html.erb
<%= link_to("<< Back to List", stops_path, :class => 'back-link') %>

<div class="stops delete">
  <h2>Delete Stop</h2>

  <%= form_for(@stop, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this stop?</p>

    <p class="reference-name"><%= f.object.stop_number %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Stop") %>
    </div>

    <% end %>
  </div>

app/views/stops/edit.html.erb
<%= link_to("<< Back to List", stops_path, :class => 'back-link') %>

<div class="stops edit">
  <h2>Update Stop</h2>

  <%= form_for(@stop) do |f| %>
    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form_buttons">
      <%= f.submit("Update Stop") %>
    </div>
  <% end %>

</div>

app/views/stops/index.html.erb
<% @page_title = "All Stops" %>

<%= link_to("<< Back to Admin Overview", admin_path, :class => 'back-link') %>

<div class="stops aindex">
  <h1>Stops</h1>

  <%= link_to("Add New Stop", new_stop_path, :class => 'action new') %>

  <p>&nbsp;</p>

  <table class="listing" summary="Stop list"

    <tr class="header">
      <th>Stop-title</th>
      <th>Stop-track (sound of stop)</th>
      <th>Time of stop</th>
      <th>Track ID LAST LINKED TO (could be linked to multiple)</th>
    </tr>

    <% @stops.each do |stop| %>
    <tr>
      <td><%= stop.stop_title %></td>
      <td><%= stop.stop_number %></td>
      <td><%= stop.stop_time %></td>
      <td><%= stop.track_id %></td>

      <td class="actions">
        <%= link_to("Show", stop_path(stop.id), :class => 'action show') %>
        <%= link_to("Edit", edit_stop_path(stop), :class => 'action edit') %>
        <%= link_to("Delete", delete_stop_path(stop), :class => 'action delete') %>
      </td>
    </tr>
  <% end %>
  </table>
</div>

app/views/stops/new.html.erb
<%= link_to("<< Back to List", stops_path, :class => 'back-link') %>

<div class="stops new">

  <h2>Create Stop</h2>

  <%= form_for(@stop) do |f| %>
    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form_buttons">
      <%= f.submit("Create Stop") %>
    </div>
  <% end %>

</div>

app/views/stops/show.html.erb
<%= link_to("<< Back to List", stops_path, :class => 'back-link') %>

<div class="stops show">
  <h2>Show Stop</h2>

  <table summary="Stop detail view">
    <tr>
      <th>Stop-title</th>
      <td><%= @stop.stop_title %></td>
    </tr>

    <tr>
      <th>Stop-track</th>
      <td><%= @stop.stop_number %></td>
    </tr>

    <tr>
      <th>Time of Stop</th>
      <td><%= @stop.stop_time %></td>
    </tr>

    <tr>
      <th>Track ID</th>
      <td><%= @stop.track_id %></td>
    </tr>

  </table>
</div>