config/routes.rb
Rails.application.routes.draw do

  #Root route:
  root :to => 'frontpage#index'

  get 'show/:permalink', :to => 'public#show', :as => 'public_show'

  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  get 'public/index'
  get 'about/index'
  get 'contact/index'
  get 'frontpage/index'
  get 'stopmaps_v/index'
  get 'stopmaps_e/index'
  
  get 'track/:id/:stop_id', :to => 'tracks#stopdelete', :as => 'delete_stop_in_track'

  #get 'sketch-map-track-list.json' => 'static#sketch-map-track-list', :defaults => { :format => 'json' }

  resources :admin_users, :except => [:show] do
    member do
      get :delete
    end
  end

  resources :tags do
    member do
      get :delete
    end
  end

  resources :stops do
    member do
      get :delete
    end
  end

  resources :tracks do
    member do
      get :delete
    end
  end

  resources :locations do
    member do
      get :delete
    end
  end

  resources :names do
    member do
      get :delete
    end
  end

  resources :finished_dates do
    member do
      get :delete
    end
  end

  resources :pitches do
    member do
      get :delete
    end
  end

  resources :stop_maps do
    member do
      get :delete
    end
  end

  resources :keys do
    member do
      get :delete
    end
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord

  has_secure_password

  has_and_belongs_to_many :tags
  has_and_belongs_to_many :tracks

  scope :sorted, lambda { order("last_name ASC", "first_name ASC") }
  
  #EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i

  validates :first_name, :presence => true,
                         :length => { :maximum => 25 }
  validates :last_name, :presence => true,
                        :length => { :maximum => 50 }
  validates :username, :presence => true,
                       :length => { :within => 8..25 },
                       :uniqueness => true
  validates :email, :presence => true,
                    :length => { :maximum => 100 },
                    #:format => EMAIL_REGEX,
                    :confirmation => true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/key.rb
class Key < ApplicationRecord

  has_secure_password

  scope :sorted, lambda { order("name ASC") }

end

app/models/stop.rb
class Stop < ApplicationRecord

  has_and_belongs_to_many :tracks

  scope :sorted, lambda { order("stop_number ASC") }

end

app/models/tag.rb
class Tag < ApplicationRecord

  has_and_belongs_to_many :tracks

  scope :visible, lambda { where(:visible => true) }
  scope :invisible, lambda { where(:visible => false) }
  scope :sorted, lambda { order("name ASC") }

end

app/models/track.rb
class Track < ApplicationRecord

  has_and_belongs_to_many :tags
  has_and_belongs_to_many :stops #må ha denne for ellers leter etter stops_tracks alfabetisk join

  has_attached_file :sound
  has_attached_file :image

  scope :visible, lambda { where(:visible => true) }
  scope :invisible, lambda { where(:visible => false) }
  scope :sorted, lambda { order("name ASC") }
  scope :sorted_by_name, lambda { order("track_number ASC", "track_version ASC") }
  scope :sorted_by_date_finished, lambda { order("date_finished DESC") }
  scope :sorted_by_pitch, lambda { order("pitch ASC") }
  scope :sorted_by_location, lambda { order("location_finished ASC") }
  scope :sorted_by_name_DESC, lambda { order("track_number DESC") }

  do_not_validate_attachment_file_type :sound
  #validates_attachment_content_type :sound, :content_type => ['audio/mp3', "audio/wav", "audio/mpeg", 'application/x-mp3'], :if => :sound?

  do_not_validate_attachment_file_type :image
  #validates_attachment :image, :content_type => [content_type: "gif", "png", "jpg", "jpeg"]

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  before_action :confirm_logged_in, :except => [:tags_publicindex]

  layout 'admin'

  def index
    @tags = Tag.sorted
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def new
    @tag = Tag.new(:name => 'Default')
  end

  def create
    # Instantiate a new object using form parameters
    @tag = Tag.new(tag_params)
    # Save object
    if @tag.save
      # If save succeeds: redirect to the index action
      redirect_to(tags_path)
    else
      # If save fails: redisplay the form so user can fix problems
      render('new')
    end
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    if @tag.update_attributes(tag_params)
      redirect_to(tag_path(@tag))
      flash[:notice] = "Tag '#{@tag.name}' updated succesfully."
    else
      render('edit')
    end
  end

  def delete
    @tag = Tag.find(params[:id])
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to(tags_path)
    flash[:notice] = "Tag '#{@tag.name}' destroyed succesfully."
  end

  private
  def tag_params
    params.require(:tag).permit(:name, :visible, :permalink)
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/frontpage_helper.rb
module FrontpageHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/helpers/pitches_helper.rb
module PitchesHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/stop_map_helper.rb
module StopMapHelper
end

app/helpers/stopmaps_e_helper.rb
module StopmapsEHelper
end

app/helpers/stopmaps_v_helper.rb
module StopmapsVHelper
end

app/helpers/stops_helper.rb
module StopsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/tags/_form.html.erb
    <table summary="Summary from fields">

      <tr>
        <th>Tag</th>
        <td><%= f.text_field(:name) %></td>
      </tr>

      <tr>
        <th>Permalink</th>
        <td><%= f.text_field(:permalink) %></td>
      </tr>

      <tr>
        <th>Visible</th>
      <td><%= f.check_box(:visible) %></td>
      </tr>
            
    </table>

app/views/tags/delete.html.erb
<%= link_to("<< Back to List", tags_path, :class => 'back-link') %>

<div class="tags delete">
  <h2>Delete Tag</h2>

  <%= form_for(@tag, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this tag?</p>

    <p class="reference-name"><%= f.object.name %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Tag") %>
    </div>

    <% end %>
  </div>

app/views/tags/edit.html.erb
<%= link_to("<< Back to List", tags_path, :class => 'back-link') %>

<div class="tags edit">
  <h2>Update Tag</h2>

  <%= form_for(@tag) do |f| %>
    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form_buttons">
      <%= f.submit("Update Tag") %>
    </div>
  <% end %>

</div>

app/views/tags/index.html.erb
<div class="tags index">
  <h1>Tags</h1>

  <%= link_to("Add New Tag", new_tag_path, :class => 'action new') %>

  <p>&nbsp;</p>

  <table class="listing" summary="Tag list"

    <tr class="header">
      <th>#</th>
      <th>Tag</th>
      <th>Permalink</th>
      <th>Visible</th>
      <th>Created</th>
      <th>Updated</th>
    </tr>

    <% @tags.each do |tag| %>
    <tr>
      <td><%= tag.id %></td>
            <td><%= tag.name %></td>
            <td class="center"><%= tag.permalink %></td>
            <td class="center"><%= status_tag(tag.visible) %></td>
            <td class="center"><%= tag.created_at.strftime("%d %b %Y %H:%M") %></td>
            <td class="center"><%= tag.updated_at.strftime("%d %b %Y %H:%M") %></td>
      <td class="actions">
        <%= link_to("Show", tag_path(tag.id), :class => 'action show') %>
        <%= link_to("Edit", edit_tag_path(tag), :class => 'action edit') %>
        <%= link_to("Delete", delete_tag_path(tag), :class => 'action delete') %>
      </td>
    </tr>
  <% end %>
  </table>
</div>

app/views/tags/new.html.erb
<%= link_to("<< Back to List", tags_path, :class => 'back-link') %>

<div class="tags new">

  <h2>Create Tag</h2>

  <%= form_for(@tag) do |f| %>
    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form_buttons">
      <%= f.submit("Create Tag") %>
    </div>
  <% end %>

</div>

app/views/tags/show.html.erb
<%= link_to("<< Back to List", tags_path, :class => 'back-link') %>

<div class="tags show">
  <h2>Show Tag</h2>

  <table summary="Tag detail view">
    <tr>
      <th>Name</th>
      <td><%= @tag.name %></td>
    </tr>
    <tr>
      <th>Permalink</th>
      <td><%= @tag.permalink %></td>
    </tr>

    <tr>
      <th>Visible</th>
    <td><%= @tag.visible %></td>
    </tr>

    <tr>
      <th>Created</th>
      <td><%= @tag.created_at %></td>
    </tr>

    <tr>
      <th>Updated</th>
      <td><%= @tag.updated_at %></td>
    </tr>
  </table>

</div>