config/routes.rb
Rails.application.routes.draw do

  #Root route:
  root :to => 'frontpage#index'

  get 'show/:permalink', :to => 'public#show', :as => 'public_show'

  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  get 'public/index'
  get 'about/index'
  get 'contact/index'
  get 'frontpage/index'
  get 'stopmaps_v/index'
  get 'stopmaps_e/index'
  
  get 'track/:id/:stop_id', :to => 'tracks#stopdelete', :as => 'delete_stop_in_track'

  #get 'sketch-map-track-list.json' => 'static#sketch-map-track-list', :defaults => { :format => 'json' }

  resources :admin_users, :except => [:show] do
    member do
      get :delete
    end
  end

  resources :tags do
    member do
      get :delete
    end
  end

  resources :stops do
    member do
      get :delete
    end
  end

  resources :tracks do
    member do
      get :delete
    end
  end

  resources :locations do
    member do
      get :delete
    end
  end

  resources :names do
    member do
      get :delete
    end
  end

  resources :finished_dates do
    member do
      get :delete
    end
  end

  resources :pitches do
    member do
      get :delete
    end
  end

  resources :stop_maps do
    member do
      get :delete
    end
  end

  resources :keys do
    member do
      get :delete
    end
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord

  has_secure_password

  has_and_belongs_to_many :tags
  has_and_belongs_to_many :tracks

  scope :sorted, lambda { order("last_name ASC", "first_name ASC") }
  
  #EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i

  validates :first_name, :presence => true,
                         :length => { :maximum => 25 }
  validates :last_name, :presence => true,
                        :length => { :maximum => 50 }
  validates :username, :presence => true,
                       :length => { :within => 8..25 },
                       :uniqueness => true
  validates :email, :presence => true,
                    :length => { :maximum => 100 },
                    #:format => EMAIL_REGEX,
                    :confirmation => true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/key.rb
class Key < ApplicationRecord

  has_secure_password

  scope :sorted, lambda { order("name ASC") }

end

app/models/stop.rb
class Stop < ApplicationRecord

  has_and_belongs_to_many :tracks

  scope :sorted, lambda { order("stop_number ASC") }

end

app/models/tag.rb
class Tag < ApplicationRecord

  has_and_belongs_to_many :tracks

  scope :visible, lambda { where(:visible => true) }
  scope :invisible, lambda { where(:visible => false) }
  scope :sorted, lambda { order("name ASC") }

end

app/models/track.rb
class Track < ApplicationRecord

  has_and_belongs_to_many :tags
  has_and_belongs_to_many :stops #må ha denne for ellers leter etter stops_tracks alfabetisk join

  has_attached_file :sound
  has_attached_file :image

  scope :visible, lambda { where(:visible => true) }
  scope :invisible, lambda { where(:visible => false) }
  scope :sorted, lambda { order("name ASC") }
  scope :sorted_by_name, lambda { order("track_number ASC", "track_version ASC") }
  scope :sorted_by_date_finished, lambda { order("date_finished DESC") }
  scope :sorted_by_pitch, lambda { order("pitch ASC") }
  scope :sorted_by_location, lambda { order("location_finished ASC") }
  scope :sorted_by_name_DESC, lambda { order("track_number DESC") }

  do_not_validate_attachment_file_type :sound
  #validates_attachment_content_type :sound, :content_type => ['audio/mp3', "audio/wav", "audio/mpeg", 'application/x-mp3'], :if => :sound?

  do_not_validate_attachment_file_type :image
  #validates_attachment :image, :content_type => [content_type: "gif", "png", "jpg", "jpeg"]

end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController

  layout 'admin'

    before_action :confirm_logged_in

    def index
      @admin_user = AdminUser.sorted
    end

    def new
      @admin_user = AdminUser.new
    end

    def create
      @admin_user = AdminUser.new(admin_user_params)
      if @admin_user.save
        flash[:notice] = "Admin User '#{@admin_user.name}' created succesfully."
        redirect_to(admin_users_path)
      else
        render('new')
      end
    end

    def edit
      @admin_user = AdminUser.find(params[:id])
    end

    def update
      @admin_user = AdminUser.find(params[:id])
      if @admin_user.update_attributes(admin_user_params)
        flash[:notice] = "Admin User '#{@admin_user.name}' updated succesfully."
        redirect_to(admin_user_path)
      else
        render('edit')
      end
    end

    def delete
      @admin_user = AdminUser.find(params[:id])
    end

    def destroy
      @admin_user = AdminUser.find(params[:id])
      @admin_user.destroy
      flash[:notice] = "Admin User '#{@admin_user.name}' destroyed succesfully."
      redirect_to(admin_users_path)
    end

    private

    def admin_user_params
      params.require(:admin_user).permit(:first_name, :last_name, :email, :username, :password)
      # Permit :password, but NOT :password_digest !!
    end

  end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/frontpage_helper.rb
module FrontpageHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/helpers/pitches_helper.rb
module PitchesHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/stop_map_helper.rb
module StopMapHelper
end

app/helpers/stopmaps_e_helper.rb
module StopmapsEHelper
end

app/helpers/stopmaps_v_helper.rb
module StopmapsVHelper
end

app/helpers/stops_helper.rb
module StopsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/admin_users/_form.html.erb
<table summary="Summary from fields">

  <tr>
    <th><%= f.label(:first_name) %></th>
    <td><%= f.text_field(:first_name, :limit => 25) %></td>
  </tr>

  <tr>
    <th><%= f.label(:last_name) %></th>
    <td><%= f.text_field(:last_name, :limit => 50) %></td>
  </tr>

  <tr>
    <th><%= f.label(:email) %></th>
    <td><%= f.text_field(:email, :limit => 100, :default => "") %></td>
  </tr>

  <tr>
    <th><%= f.label(:username) %></th>
    <td><%= f.text_field(:username, :limit => 25) %></td>
  </tr>

  <tr>
    <th><%= f.label(:password) %></th>
    <td><%= f.password_field(:password, :limit => 25) %></td>
  </tr>

</table>

app/views/admin_users/delete.html.erb
<% @page_title = "Delete Admin User" %>

<%= link_to("<< Back to List", admin_users_path, :class => 'back-link') %>

<div class="admin_users delete">
  <h2>Delete Admin User</h2>

  <%= form_for(@admin_user, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this admin user?</p>

    <p class="reference-name"><%= f.object.name %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Admin User") %>
    </div>

    <% end %>
  </div>

app/views/admin_users/edit.html.erb
<% @page_title = "Update Admin User" %>

<%= link_to("<< Back to List", admin_users_path, :class => 'back-link') %>

<div class="admin_users edit">
  <h2>Update Admin User</h2>

  <%= form_for(@admin_user) do |f| %>
    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form_buttons">
      <%= f.submit("Update Admin User") %>
    </div>
  <% end %>

</div>

app/views/admin_users/index.html.erb
<% @page_title = "All Admin Users" %>

<%= link_to("<< Back to Admin Overview", admin_path, :class => 'back-link') %>

<div class="admin-users aindex">
  <h1>Admin Users</h1>

  <%= link_to("Add New Admin User", new_admin_user_path, :class => 'action new') %>
  <p>&nbsp;</p>
  <div><%= pluralize(@admin_user.size, 'admin user') %> found</div>
  <p>&nbsp;</p>
  <table class="listing" summary="Admin User list">
    <tr>
      <th>Username</th>
      <th>Last Name</th>
      <th>First Name</th>
      <th>Email</th>
      <th>Actions</th>
    </tr>

    <% @admin_user.each do |admin_user| %>

    <tr>
      <td><%= admin_user.username %></td>
      <td><%= admin_user.last_name %></td>
      <td><%= admin_user.first_name %></td>
      <td><%= mail_to(admin_user.email) %></td>
      <td class="actions">
        <%= link_to("Edit", edit_admin_user_path(admin_user), :class => 'action edit') %>
        <%= link_to("Delete", delete_admin_user_path(admin_user), :class => 'action delete') %>
      </td>
    </tr>
  <% end %>
  </table>
</div>

app/views/admin_users/new.html.erb
<% @page_title = "New Admin User" %>

<%= link_to("<< Back to List", admin_users_path, :class => 'back-link') %>

<div class="admin-users new">

  <h2>Create Admin User</h2>

  <%= form_for(@admin_user) do |f| %>
    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form_buttons">
      <%= f.submit("Create Admin User") %>
    </div>

  <% end %>

</div>